window.AIRPORTS = [
  {
    id: "vie",
    name: "Vienna",
    fullName: "Vienna International",
    code: "VIE",
    country: "Austria",
    layout: "single",
    cols: 3,
    rows: 3,
    landingRunway: "main",
    takeoffRunway: "main",
    runways: [
      { id: "main", start: "11", end: "29", badge: "RWY 11/29", role: "shared" },
    ],
    airlines: [
      // Austrian / Wizz = short-haul only (no widebody / heavy / jumbo)
      { id: "os", name: "Austrian", flag: "AT", weight: 70, minLevel: 1, maxLevel: 7 },
      { id: "wj", name: "Wizz Air", flag: "HU", weight: 18, minLevel: 6, maxLevel: 7 },
      // L8–L10 big metal at VIE
      { id: "lh", name: "Lufthansa", flag: "DE", weight: 45, minLevel: 5, maxLevel: 10 },
      { id: "lx", name: "Swiss", flag: "CH", weight: 30, minLevel: 5, maxLevel: 10 },
    ],
    theme: {
      skyTop: "#5f92b8",
      skyMid: "#9ec6de",
      skyBot: "#d5e8f3",
      accent: "#ed1c24",
      tarmac: "#4a5564",
      apronDeep: "#2a3140",
    },
  },
  {
    id: "ams",
    name: "Amsterdam",
    fullName: "Amsterdam Schiphol",
    code: "AMS",
    country: "Netherlands",
    layout: "dual",
    cols: 3,
    rows: 3,
    mask: [false, true, false, true, true, true, false, true, false],
    landingRunway: "landing",
    takeoffRunway: "takeoff",
    runways: [
      { id: "landing", start: "18", end: "36", badge: "Arrivals", role: "landing" },
      { id: "takeoff", start: "09", end: "27", badge: "Departures", role: "takeoff" },
    ],
    airlines: [
      { id: "kl", name: "KLM", flag: "NL", weight: 42, minLevel: 1, maxLevel: 10 },
      { id: "wa", name: "KLM Cityhopper", flag: "NL", weight: 35, minLevel: 1, maxLevel: 5 },
      { id: "hv", name: "Transavia", flag: "NL", weight: 20, minLevel: 6, maxLevel: 7 },
      { id: "u2", name: "easyJet", flag: "GB", weight: 12, minLevel: 6, maxLevel: 7 },
      { id: "ba", name: "British Airways", flag: "GB", weight: 18, minLevel: 7, maxLevel: 10 },
    ],
    theme: {
      skyTop: "#4e86b8",
      skyMid: "#8eb9d8",
      skyBot: "#cfe3f2",
      accent: "#ff6600",
      tarmac: "#45505e",
      apronDeep: "#273040",
    },
  },
  {
    id: "lhr",
    name: "London",
    fullName: "London Heathrow",
    code: "LHR",
    country: "United Kingdom",
    layout: "dual",
    cols: 4,
    rows: 2,
    landingRunway: "landing",
    takeoffRunway: "takeoff",
    runways: [
      { id: "landing", start: "09L", end: "27R", badge: "Arrivals", role: "landing" },
      { id: "takeoff", start: "09R", end: "27L", badge: "Departures", role: "takeoff" },
    ],
    airlines: [
      { id: "ba", name: "British Airways", flag: "GB", weight: 75, minLevel: 1, maxLevel: 10 },
      { id: "log", name: "Loganair", flag: "GB", weight: 14, minLevel: 1, maxLevel: 4 },
      { id: "ei", name: "Aer Lingus", flag: "IE", weight: 10, minLevel: 5, maxLevel: 8 },
      { id: "vs", name: "Virgin Atlantic", flag: "GB", weight: 14, minLevel: 8, maxLevel: 10 },
      { id: "af", name: "Air France", flag: "FR", weight: 8, minLevel: 7, maxLevel: 10 },
    ],
    theme: {
      skyTop: "#607895",
      skyMid: "#8fa4b8",
      skyBot: "#c8d4de",
      accent: "#cf142b",
      tarmac: "#3f4754",
      apronDeep: "#242a35",
    },
  },
  {
    id: "dxb",
    name: "Dubai",
    fullName: "Dubai International",
    code: "DXB",
    country: "United Arab Emirates",
    layout: "dual",
    cols: 4,
    rows: 3,
    landingRunway: "landing",
    takeoffRunway: "takeoff",
    runways: [
      { id: "landing", start: "12L", end: "30R", badge: "Arrivals", role: "landing" },
      { id: "takeoff", start: "12R", end: "30L", badge: "Departures", role: "takeoff" },
    ],
    airlines: [
      { id: "ek", name: "Emirates", flag: "AE", weight: 55, minLevel: 8, maxLevel: 10 },
      { id: "fz", name: "flydubai", flag: "AE", weight: 35, minLevel: 5, maxLevel: 7 },
      { id: "g9", name: "Air Arabia", flag: "AE", weight: 12, minLevel: 5, maxLevel: 7 },
      { id: "qr", name: "Qatar Airways", flag: "QA", weight: 22, minLevel: 7, maxLevel: 10 },
      { id: "tk", name: "Turkish Airlines", flag: "TR", weight: 16, minLevel: 6, maxLevel: 10 },
    ],
    theme: {
      skyTop: "#2f7db5",
      skyMid: "#6eb0d4",
      skyBot: "#e8c98a",
      accent: "#c4a35a",
      tarmac: "#5a5044",
      apronDeep: "#3a342c",
    },
  },
  {
    id: "hnd",
    name: "Tokyo",
    fullName: "Tokyo Haneda",
    code: "HND",
    country: "Japan",
    layout: "side",
    cols: 3,
    rows: 3,
    mask: [true, true, false, true, true, false, true, true, true],
    landingRunway: "main",
    takeoffRunway: "main",
    runways: [
      { id: "main", start: "16", end: "34", badge: "RWY 16/34", role: "shared", vertical: true },
    ],
    airlines: [
      { id: "jl", name: "Japan Airlines", flag: "JP", weight: 40, minLevel: 1, maxLevel: 10 },
      { id: "nh", name: "ANA", flag: "JP", weight: 40, minLevel: 1, maxLevel: 10 },
      { id: "jc", name: "J-Air", flag: "JP", weight: 18, minLevel: 1, maxLevel: 5 },
      { id: "ke", name: "Korean Air", flag: "KR", weight: 12, minLevel: 6, maxLevel: 10 },
    ],
    theme: {
      skyTop: "#4a6fa5",
      skyMid: "#7fa0c8",
      skyBot: "#d6e0ec",
      accent: "#bc002d",
      tarmac: "#454d5c",
      apronDeep: "#262d3a",
    },
  },
  {
    id: "jfk",
    name: "New York",
    fullName: "John F. Kennedy",
    code: "JFK",
    country: "United States",
    layout: "cross",
    cols: 3,
    rows: 3,
    mask: [false, true, false, true, true, true, false, true, false],
    landingRunway: "landing",
    takeoffRunway: "takeoff",
    runways: [
      { id: "landing", start: "04L", end: "22R", badge: "Arrivals", role: "landing" },
      { id: "takeoff", start: "13L", end: "31R", badge: "Departures", role: "takeoff", vertical: true },
    ],
    airlines: [
      { id: "dl", name: "Delta", flag: "US", weight: 32, minLevel: 5, maxLevel: 10 },
      { id: "aa", name: "American", flag: "US", weight: 30, minLevel: 5, maxLevel: 10 },
      { id: "b6", name: "JetBlue", flag: "US", weight: 22, minLevel: 5, maxLevel: 7 },
      { id: "9k", name: "Cape Air", flag: "US", weight: 20, minLevel: 1, maxLevel: 3 },
      { id: "ba", name: "British Airways", flag: "GB", weight: 14, minLevel: 8, maxLevel: 10 },
    ],
    theme: {
      skyTop: "#3d6ea5",
      skyMid: "#6f9bc4",
      skyBot: "#b9d2e8",
      accent: "#1e4d8c",
      tarmac: "#404858",
      apronDeep: "#222833",
    },
  },
  {
    id: "syd",
    name: "Sydney",
    fullName: "Sydney Kingsford Smith",
    code: "SYD",
    country: "Australia",
    layout: "dual",
    cols: 3,
    rows: 3,
    landingRunway: "landing",
    takeoffRunway: "takeoff",
    runways: [
      { id: "landing", start: "16R", end: "34L", badge: "Arrivals", role: "landing" },
      { id: "takeoff", start: "07", end: "25", badge: "Departures", role: "takeoff" },
    ],
    airlines: [
      { id: "qf", name: "Qantas", flag: "AU", weight: 40, minLevel: 1, maxLevel: 10 },
      { id: "xl", name: "QantasLink", flag: "AU", weight: 30, minLevel: 1, maxLevel: 5 },
      { id: "va", name: "Virgin Australia", flag: "AU", weight: 18, minLevel: 5, maxLevel: 7 },
      { id: "jq", name: "Jetstar", flag: "AU", weight: 14, minLevel: 6, maxLevel: 7 },
      { id: "nz", name: "Air New Zealand", flag: "NZ", weight: 16, minLevel: 6, maxLevel: 10 },
    ],
    theme: {
      skyTop: "#2f86b8",
      skyMid: "#62b4d8",
      skyBot: "#d8ef8a",
      accent: "#00843d",
      tarmac: "#4a5a48",
      apronDeep: "#2c382c",
    },
  },
  {
    id: "sin",
    name: "Singapore",
    fullName: "Singapore Changi",
    code: "SIN",
    country: "Singapore",
    layout: "dual",
    cols: 3,
    rows: 4,
    mask: [
      false, true, false,
      true, true, true,
      true, true, true,
      false, true, false,
    ],
    landingRunway: "landing",
    takeoffRunway: "takeoff",
    runways: [
      { id: "landing", start: "02L", end: "20R", badge: "Arrivals", role: "landing" },
      { id: "takeoff", start: "02C", end: "20C", badge: "Departures", role: "takeoff" },
    ],
    airlines: [
      { id: "sq", name: "Singapore Airlines", flag: "SG", weight: 50, minLevel: 7, maxLevel: 10 },
      { id: "tr", name: "Scoot", flag: "SG", weight: 22, minLevel: 6, maxLevel: 8 },
      { id: "mi", name: "SilkAir", flag: "SG", weight: 18, minLevel: 4, maxLevel: 7 },
      { id: "mh", name: "Malaysia Airlines", flag: "MY", weight: 14, minLevel: 6, maxLevel: 10 },
      { id: "ga", name: "Garuda", flag: "ID", weight: 10, minLevel: 6, maxLevel: 10 },
    ],
    theme: {
      skyTop: "#1f7a8c",
      skyMid: "#4da6b0",
      skyBot: "#c7ebe4",
      accent: "#ef3340",
      tarmac: "#3d4f52",
      apronDeep: "#243236",
    },
  },
];
